dist: trusty
sudo: false
language: minimal

branches:
  only:
    - master
    - /^v[\d.-]+$/

notifications:
  email: false

script:
  - git diff --check $TRAVIS_COMMIT_RANGE

before_deploy:
  - curl -L "https://github.com/AbigailBuccaneer/gmad-build/releases/download/v20180201/gmad_linux" -o "$HOME/gmad_linux"
  - chmod +x "$HOME/gmad_linux"
  - $HOME/gmad_linux create -folder . -out advdupe2.gma

deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: EK1zfysVaXMB52mfDlPFwaqM7zGJE/G1iFKyjWMV20GDqZkE9/g+KlwwaRuz7q0NX0KgGuc7dk5j0JQXTg3Z14kUYdIYSq3tDkp0YBeePqVGUgQoA19ZFPlBdZEV0EF3dDHMYmErNYBuCYW7Twrzy++WgzghCcthXaV9jboF5lk=
  file: advdupe2.gma
  on:
    repo: wiremod/advdupe2
    tags: true
